name: city_weather
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.1.0
  retrofit: ^3.0.0
  dio: ^4.0.6
  intl: ^0.17.0
  json_annotation: ^4.6.0
  pretty_dio_logger: ^1.1.1
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_slidable: ^2.0.0
  connectivity_plus: ^2.0.2 
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  email_validator: ^2.1.17

dev_dependencies:
  lint: ^1.5.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3+1
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/location.jpg
    - assets/weather.jpg
